### ISSUE TITLE
Add function for merging datasets

### ISSUE THREAD

**Issue by krlmlr** [cynkra/SwissCommunes#1]
- Merge two data sets based on commune IDs
- Aggregate using a function (default: `sum`)
- Make sure that factor levels match

**Comment by TSchiefer** [comment]
@krlmlr Is this solved with `swcGetMapping()`?

**Comment by krlmlr** [comment]
I think it's solved with `swc_get_merger_mapping_table()`; we should describe how to aggregate in `vignette("SwissCommunes")` .
