### ISSUE TITLE
Rename to munch

### ISSUE THREAD

**Issue by krlmlr** [cynkra/SwissCommunes#21]
- [ ] Replace everywhere
- [ ] GitHub homepage
- [ ] Create stub for old pkgdown content
- [ ] ~~Replace `swc_()` prefix~~
- [ ] Clean up README

**Comment by TSchiefer** [comment]
good name :)

how to replace the prefix `swc_`?

**Comment by TSchiefer** [comment]
What about `swc_` -> `mch_`? just an idea, really no strong opinion here

**Comment by krlmlr** [comment]
Naming decision postponed to #32.
