### ISSUE TITLE
Fix CI/CD

### ISSUE THREAD

**Issue by krlmlr** [cynkra/SwissCommunes#39]
I changed `cantons` to `get_cantons()`, need to clean up.

**Comment by TSchiefer** [comment]
One problem with the check is:
```
❯ checking installed package size ... NOTE
    installed size is 18.8Mb
    sub-directories of 1Mb or more:
      csv  18.1Mb
```
Can we do anything about this? Maybe store as zip?

**Comment by krlmlr** [comment]
Please add `error_on <- "warning"` to `R-CMD-check.yaml` for now.

**Comment by krlmlr** [comment]
And also to `...-dev.yaml` .

**Comment by TSchiefer** [comment]
in `R/get_merger_mapping_table.R` we have this:
```r
  if (Sys.getenv("IN_PKGDOWN") == "") {
    readr::write_csv(mutation_init, new_csv_file("debug-init", end_year))
  }
```
and one for debug-base.

do we still need this? (leads to an error in the R-CMD-check)

**Comment by krlmlr** [comment]
I think we can remove it for now, also the files.

**Comment by TSchiefer** [comment]
There is now one check failing, on ubuntu-18.04 (devel). No idea why the example fails in this case whereas it works fine in all other setups.
If you think we should investigate that it would be nice if you could give me a pointer how to tackle this. 
If we can ignore this one failed case, I would consider this issue done.

**Comment by krlmlr** [comment]
This looks odd. Can you please add build matrix entries for R-devel on macOS and Windows, to investigate if this occurs across platforms?

**Comment by TSchiefer** [comment]
Occurs across platforms

**Comment by krlmlr** [comment]
I can replicate locally with R devel, will take a look.
